# Pré processamento dos conjuntos de dados

In [3]:
import pandas as pd
import os
# from utils import get_workdir, bitarray_to_string
# from thermometer import Thermometer
from sklearn.model_selection import train_test_split

data = pd.read_csv(f"../dataset/abalone/data.csv")
data

,sex,len,diam,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [5]:
data.groupby("rings").count()

,sex,len,diam,height,whole_weight,shucked_weight,viscera_weight,shell_weight
rings,,,,,,,,
1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1
3,15,15,15,15,15,15,15,15
4,57,57,57,57,57,57,57,57
5,115,115,115,115,115,115,115,115
6,259,259,259,259,259,259,259,259
7,391,391,391,391,391,391,391,391
8,568,568,568,568,568,568,568,568
9,689,689,689,689,689,689,689,689
10,634,634,634,634,634,634,634,634
11,487,487,487,487,487,487,487,487
12,267,267,267,267,267,267,267,267
13,203,203,203,203,203,203,203,203
14,126,126,126,126,126,126,126,126
15,103,103,103,103,103,103,103,103
16,67,67,67,67,67,67,67,67
17,58,58,58,58,58,58,58,58
18,42,42,42,42,42,42,42,42
19,32,32,32,32,32,32,32,32
20,26,26,26,26,26,26,26,26
21,14,14,14,14,14,14,14,14
22,6,6,6,6,6,6,6,6
23,9,9,9,9,9,9,9,9
24,2,2,2,2,2,2,2,2
25,1,1,1,1,1,1,1,1
26,1,1,1,1,1,1,1,1
27,2,2,2,2,2,2,2,2
29,1,1,1,1,1,1,1,1